#!/usr/bin/env ruby

require 'rack'
require 'tilt'
require File.join(File.dirname(__FILE__), 'rack-add-headers')

%w{gemspec rb}.each do |ext|
  Rack::Mime::MIME_TYPES.merge! ".#{ext}" => 'text/plain'
end

app = Rack::Builder.app do

  files = Rack::Directory.new('.')

  use AddHeaders, 'X-Content-Type-Options' => 'nosniff', 'Cache-Control' => 'no-store'
  
  run lambda { |env|
    path = env['PATH_INFO'][1..-1]
  
    begin
      return [200, {"Content-Type" => "text/html"}, [Tilt.new(path).render]] if Tilt[path]
    rescue Errno::ENOENT
      #404 will be created automatically
    rescue LoadError => le
      return [500, {"Content-Type" => "text/plain"}, ["#{le}\nYou need to install the appropriate gem."]]
    end

    files.call(env)
  }

end

Rack::Server.start :app => app, :Port => 9292
