#!/usr/bin/env ruby

require 'rack'
require 'tilt'

#this might be useful, but doesn't work in chrome
Rack::Mime::MIME_TYPES.merge! '.gemspec' => 'text/plain'

@files = Rack::Directory.new('.')

app = lambda do |env|
  path = env['PATH_INFO'][1..-1]
  
  begin
    return [200, {"Content-Type" => "text/html"}, [Tilt.new(path).render]] if Tilt[path]
  rescue Errno::ENOENT
    #404 will be created automatically
  rescue LoadError => le
    return [500, {"Content-Type" => "text/plain"}, ["#{le}\nYou need to install the appropriate gem."]]
  end 
  
  @files.call(env)
end

Rack::Server.start :app => app, :Port => 9292

  