#!/usr/bin/env ruby

require 'sinatra'
require 'rdiscount'

enable :run

get "/" do
  @files = Dir["*.{md,markdown,mkd}"]
  if @files == []
    "No markdown files found."
  else
    erb :index
  end
end

get %r{^/((.*)\.(md|markdown|mkd)$)} do
  begin
    md = File.read params[:captures][0]
  rescue Errno::ENOENT
    return "No such file: #{params[:captures][0]}"
  end
  
  Markdown.new(md).to_html  
end

__END__

@@index

<ul>
<% @files.each do |f| %>
  <%="<li><a href='#{f}'>#{f}</a></li>"%>
<%end%>
</ul>
  